# Generated by Django 3.1.7 on 2021-04-06 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_service', '0002_auto_20210406_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=32)),
                ('course_cover', models.CharField(max_length=255)),
                ('tuition', models.DecimalField(decimal_places=3, max_digits=3)),
                ('course_chapter', models.CharField(max_length=255)),
                ('single_course', models.CharField(max_length=255)),
                ('course_foundation', models.CharField(max_length=32)),
                ('course_video', models.CharField(max_length=255)),
                ('course_author', models.CharField(max_length=64)),
                ('course_label', models.CharField(max_length=128)),
                ('play_num', models.IntegerField()),
                ('pay_num', models.IntegerField()),
                ('registration_time', models.DateTimeField()),
                ('registrant', models.CharField(max_length=255)),
                ('revision_time', models.DateTimeField()),
                ('reviser', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_service.user_info')),
            ],
        ),
    ]
