# Generated by Django 3.1.7 on 2021-04-06 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_service', '0002_auto_20210406_1701'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='publicity_pic',
            fields=[
                ('Publicity_id', models.AutoField(primary_key=True, serialize=False)),
                ('Publicity_pic', models.CharField(max_length=255)),
                ('jump_url', models.CharField(max_length=255)),
                ('registration_time', models.DateTimeField()),
                ('registrant', models.CharField(max_length=255)),
                ('revision_time', models.DateTimeField()),
                ('reviser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='search_recommend',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommend_course', models.CharField(max_length=255)),
                ('registration_time', models.DateTimeField()),
                ('registrant', models.CharField(max_length=255)),
                ('revision_time', models.DateTimeField()),
                ('reviser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField()),
                ('registrant', models.CharField(max_length=255)),
                ('revision_time', models.DateTimeField()),
                ('reviser', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course_info')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_service.user_info')),
            ],
        ),
    ]
