# Generated by Django 3.1.7 on 2021-04-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
